image:
  - Visual Studio 2019
  - macOS
  - Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: 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

install:
  - pip install -r requirements.txt

build_script:
  - pyinstaller lyricsApp.py --name counter --noconsole --noconfirm --onefile --icon ./icon.png

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
  - matrix:
      only:
        - image: Visual Studio 2019

    after_build:
      - 7z a loveworldlyricapp.zip %CD%\dist\*.exe

    artifacts:
      - path: loveworldlyricapp.zip

  #
  #   macOS package
  #
  - matrix:
      only:
        - image: macOS

    after_build:
      - tar -czvf loveworldlyricapp.tar.gz -C dist counter.app

    artifacts:
      - path: loveworldlyricapp.tar.gz

  #
  #   Linux package
  #
  - matrix:
      only:
        - image: Ubuntu

    after_build:
      - tar -czvf loveworldlyricapp.tar.gz -C dist counter

    artifacts:
      - path: loveworldlyricapp.tar.gz

